platform :ios, "7.1"
deployment_target = '6.0'
pod 'ASIHTTPRequest', '~> 1.8.2'
pod 'MBProgressHUD', '~> 0.8'
pod 'Toast', '~> 2.2'
pod 'PinYin4Objc', '~> 1.1.1'
pod 'SIAlertView', '~> 1.3'
pod 'TPKeyboardAvoiding', '~> 1.2.3'
pod 'MagicalRecord', '~> 2.2'
pod 'CocoaAsyncSocket', '~> 7.3.4'
pod 'Appirater'
pod 'iOS-Slide-Menu', '~> 1.4.2'
pod 'CHTCollectionViewWaterfallLayout'
